image:
  - Visual Studio 2017

environment:
  global:
    VERSION: 1.4.13
  matrix:
  - platform: x64
    TARGET_ARCH: x86_64
    CFLAGS: -m64
    PATH: C:\msys64\mingw64\bin\;C:\msys64\usr\bin\;$(PATH)
    PACKAGES: mingw-w64-x86_64-gcc mingw-w64-x86_64-toolchain mingw-w64-x86_64-libtool autoconf automake make

skip_non_tags: true

branches:
  only:
    - master
    - "/^v\\d+(\\.\\d+)+$/"

install:
  - >
    sh -c "
    pacman --needed --noconfirm -S zip unzip %PACKAGES%
    && curl -L http://bodge.borodust.org/files/install.sh | sh
    && ln -sf $HOME/opt/lisp/run-sbcl.sh ~/bin/sbcl
    "

build_script:
  - sh -c "./make.sh %VERSION%"


# artifacts:
#   - path: "%GAMEKIT_ARTIFACT%"
#     name: release_archive

# deploy:
#   provider: GitHub
#   release: $(APPVEYOR_REPO_TAG_NAME)
#   tag: $(APPVEYOR_REPO_TAG_NAME)
#   description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
#   auth_token:
#     secure: Z5XWjDOBlCrmfz3SQAjnLKtdgI5B2b/owJhRPNWYGrI+qwVNbBc4cZiroBZReWP7
#   artifact: release_archive
#   force_update: true
#   draft: false
#   prerelease: false
#   on:
#     appveyor_repo_tag: true
